name: Diff Changes

on: [push]

permissions:
  contents: write

jobs:
  diff_latex:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4

    - run: |
        cp -r . _original
        cd _original && git checkout compass-2025-submission

    - run: echo "\$pdflatex = \"latexdiff main.tex main2.tex > main-d.tex; pdflatex %O  main-d\"" > test

    - name: Build LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        working_directory: build
        root_file: main.tex
        latexmk_shell_escape: true

    - name: Package Diffed LaTeX
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
        single-commit: false
        branch: diff