name: Diff Changes

on: [push]

permissions:
  contents: write

jobs:
  diff_latex:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - run: |
        ls -lah
        ls -lah _original
        ls -lah _original/metadata
        cat  _original/metadata/ccs-keywords-teaser-revise.tex
        cp ./_original/‎metadata/ccs-keywords-teaser-revise.tex ./‎metadata/ccs-keywords-teaser-revise.tex

    - name: Build LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        pre_compile: latexpand compass2025.tex > new.tex && cd _original && latexpand compass2025.tex > old.tex && cd .. && latexdiff _original/old.tex new.tex > diff.tex
        root_file: diff.tex
        latexmk_shell_escape: true
    
    - run: |
        mkdir build
        cp diff.pdf build/

    - name: Package Diffed LaTeX
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
        single-commit: false
        branch: diff
