name: Diff Changes

on: [push]

permissions:
  contents: write

jobs:
  diff_latex:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Build LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        pre_compile: python diff.py
        root_file: compass2025.tex
        latexmk_shell_escape: true
    
    - run: |
        mkdir build
        cp *.pdf build/

    - name: Package Diffed LaTeX
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
        single-commit: false
        branch: diff