name: Diff Changes

on: [push]

permissions:
  contents: write

jobs:
  diff_latex:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - run: echo "\$pdflatex = \"latexdiff _original/compass2025.tex compass2025.tex > main-d.tex; pdflatex %O  main-d\"" > latexmkrc

    - name: Build LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        pre_compile: latexdiff _original/compass2025.tex compass2025.tex > main-d.tex
        root_file: main-d.tex
        latexmk_shell_escape: true

    - name: Package Diffed LaTeX
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        single-commit: false
        branch: diff